// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWRZrGHaZYHi5OIXF5yddorRLM47fwyBw',
    appId: '1:286614746391:web:150baad658b2a08dae3352',
    messagingSenderId: '286614746391',
    projectId: 'final-project-f5a0f',
    authDomain: 'final-project-f5a0f.firebaseapp.com',
    storageBucket: 'final-project-f5a0f.appspot.com',
    measurementId: 'G-RGN05YM4FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOUewCa3-jpXBvY9aa7Pdif8eIxv2DyVA',
    appId: '1:286614746391:android:f9193468153a2980ae3352',
    messagingSenderId: '286614746391',
    projectId: 'final-project-f5a0f',
    storageBucket: 'final-project-f5a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9vKmtdC_wBbTxN8akVWLxCjRcT2S0rFg',
    appId: '1:286614746391:ios:6abdf5251316364bae3352',
    messagingSenderId: '286614746391',
    projectId: 'final-project-f5a0f',
    storageBucket: 'final-project-f5a0f.appspot.com',
    iosClientId: '286614746391-veqou0tdvcojhbv762o188m55ruvh4fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9vKmtdC_wBbTxN8akVWLxCjRcT2S0rFg',
    appId: '1:286614746391:ios:6abdf5251316364bae3352',
    messagingSenderId: '286614746391',
    projectId: 'final-project-f5a0f',
    storageBucket: 'final-project-f5a0f.appspot.com',
    iosClientId: '286614746391-veqou0tdvcojhbv762o188m55ruvh4fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWRZrGHaZYHi5OIXF5yddorRLM47fwyBw',
    appId: '1:286614746391:web:114d7580f135ba38ae3352',
    messagingSenderId: '286614746391',
    projectId: 'final-project-f5a0f',
    authDomain: 'final-project-f5a0f.firebaseapp.com',
    storageBucket: 'final-project-f5a0f.appspot.com',
    measurementId: 'G-CWF48DTJLW',
  );

}